### ISSUE TITLE
[C++] Doesn't detect functions with struct parameters

### ISSUE THREAD

**Issue by Hirse** [terryyin/lizard#134]
While running this tool on some MySQL code, I found that the following function was not detected in the output:
```c++
int Append_block_log_event::exec_event(struct st_relay_log_info* rli)
{
    ...
}
```

Only after removing the `struct`-keyword for testing, it was picked up and shown in the result.

**Comment by terryyin** [comment]
@Hirse thanks for the issue. It's fixed by https://github.com/terryyin/lizard/commit/524fc21bdeb547c08bc19471041ca9842533af80 now. I also created a new Pypi release. The bug is brought by a refactoring not too long ago.

I didn't close the issue manually myself. Surprisingly, when I commit my code with a comment "fix #133", the issue is closed automatically. So please still confirm the fix if you can. Thanks:-)

**Comment by Hirse** [comment]
Thanks, for this quick reaction. :smile: 
I will let you know when I am able to confirm it.

**Comment by Hirse** [comment]
fyi :wink: 
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by terryyin** [comment]
OK, I thought closing issues without first trying to agree with the issue creator is a bit rude. Now it seems a common practice:-)
