### ISSUE TITLE
Exclude multiple path

### ISSUE THREAD

**Issue by salmojunior** [terryyin/lizard#260]
What is the pattern to user `--exclude` for multiple path? I've trying many examples but none of them works.

**Comment by terryyin** [comment]
You ca use —exclude or -X multiple times in a commend.

**Comment by salmojunior** [comment]
It doesn't work. Actually the command runs but when I check the report file it contains results from all files, not even excluding the first `--exclude` argument which is working when added alone.

**Comment by terryyin** [comment]
Can you show me your command?

**Comment by salmojunior** [comment]
Hi @terryyin,

Thanks helping me. This command works:
`lizard ./Source -l swift --xml > ./reports/lizard-report.xml --exclude './Pods/*' --exclude './Pods/*'`

but if I try to add a new `--exclude` argument like below example it stops ignoring even Pods folder.

`lizard ./Source -l swift --xml > ./reports/lizard-report.xml --exclude './Pods/*' --exclude './Pods/*' --exclude './CodeGenerated/*'`

**Comment by terryyin** [comment]
I checked the code and experimented a bit on my side. It seems working fine.

Perhaps the patterns you are using doesn’t match the folder since ‘./‘ is more current folder, but you are analysing ‘./Scoure’ folder only. Try changing . To *. The pattern matching use this function:
https://docs.python.org/3.4/library/fnmatch.html

**Comment by salmojunior** [comment]
it worked :) 

Thanks a lot @terryyin
